### ISSUE TITLE
请问有关勋章

### ISSUE THREAD

**Issue by chy89224** [Vector000/bilive_client#10]
可以用银瓜子兑换勋章的功能吗

**Comment by ShmilyChen** [comment]
可以用银瓜子兑换硬币，然后用硬币投视频来换勋章

**Comment by Vector000** [comment]
可以做，但是挺麻烦，要在网页上弄一个口子，我考虑一下要不要做


―     Sent from Windows 11

________________________________
发件人: chy89224 <notifications@github.com>
发送时间: Friday, April 12, 2019 9:49:34 AM
收件人: Vector000/bilive_client
抄送: Subscribed
主题: [Vector000/bilive_client] 请问有关勋章 (#10)


可以用银瓜子兑换勋章的功能吗

―

**Comment by chy89224** [comment]
请问开了老爷挂机每五分钟涨经验是自动开启还是在哪手动开启的

**Comment by Vector000** [comment]
打开开关自动挂经验
发件人: chy89224<mailto:notifications@github.com>
发送时间: 2019年4月13日 8:59
收件人: Vector000/bilive_client<mailto:bilive_client@noreply.github.com>
抄送: Vector000<mailto:victorguo23@hotmail.com>; Comment<mailto:comment@noreply.github.com>
主题: Re: [Vector000/bilive_client] 请问有关勋章 (#10)


请问开了老爷挂机每五分钟涨经验是自动开启还是在哪手动开启的

―
