### ISSUE TITLE
大佬打算什么时候合并分支呀

### ISSUE THREAD

**Issue by ShmilyChen** [Vector000/bilive_client#16]

**Comment by Vector000** [comment]
实物宝箱还没有测试过，可能还要改，暂时莫得合并（咕）

发送自 Windows 11

________________________________
发件人: ShmilyChen <notifications@github.com>
发送时间: Monday, April 29, 2019 5:29:53 PM
收件人: Vector000/bilive_client
抄送: Subscribed
主题: [Vector000/bilive_client] 大佬打算什么时候合并分支呀 (#16)


―
