### ISSUE TITLE
安卓Termux挂机更新检测问题

### ISSUE THREAD

**Issue by Womsxd** [Vector000/bilive_client#17]
安卓手机可以通过安装termux进行挂机，但是会出现"WARNING: linker: Unsupported flags DT_FLAGS_1=0x8"导致更新检测失败，但是报错出现后才开始获取+返回

**Comment by Womsxd** [comment]
系统是安卓5.1

**Comment by Vector000** [comment]
查了一下，这是安卓5.1的锅，详情→https://github.com/termux/termux-packages/issues/2846
其实还是建议用6.0+的安卓跑这个

发送自 Windows 11

________________________________
发件人: Womsxd <notifications@github.com>
发送时间: Wednesday, May 1, 2019 9:27:15 PM
收件人: Vector000/bilive_client
抄送: Subscribed
主题: Re: [Vector000/bilive_client] 安卓Termux挂机更新检测问题 (#17)


系统是安卓5.1

―

**Comment by Womsxd** [comment]
可否更新检测插件屏蔽这个返回等待下一个返回，拿旧手机跑的
