### ISSUE TITLE
大佬有空的话可以做自动转扭蛋的功能吗？

### ISSUE THREAD

**Issue by BugKun** [Vector000/bilive_client#21]
不知不觉扭蛋越来越多了，很多时候忘记去扭一扭了。
希望大佬有空可以加一下这个功能。

**Comment by Vector000** [comment]
自动扭蛋实现不难，但是条件判断有点麻烦，因为分普通和梦幻
大佬是觉得做成每天都扭完，还是只扭梦幻的样子（我是手扭的2333）

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: nopast <notifications@github.com>
发送时间: Monday, May 6, 2019 5:10:44 PM
收件人: Vector000/bilive_client
抄送: Subscribed
主题: [Vector000/bilive_client] 大佬有空的话可以做自动转扭蛋的功能吗？ (#21)


不知不觉扭蛋越来越多了，很多时候忘记去扭一扭了。
希望大佬有空可以加一下这个功能。

―

**Comment by BugKun** [comment]
能定期自动扭就行，时间间隔不重要。
主要是自己经常忘记去扭。

**Comment by ShmilyChen** [comment]
只用扭梦幻吧，毕竟梦幻才会清空，普通不会

**Comment by BugKun** [comment]
没问题，我还以为是都会清的
