### ISSUE TITLE
今天突然键入npm start出现错误，请问怎么办

### ISSUE THREAD

**Issue by chy89224** [Vector000/bilive_client#23]
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bilive_client@2.1.0 build:view: `webpack --config docs/webpack.conf.js
&& npm-run-posix-or-windows copy:view`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bilive_client@2.1.0 build:view script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\chy\AppData\Roaming\npm-cache\_logs\2019-05-10T01_44_13_18
3Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bilive_client@2.1.0 prestart: `npm run clean && npm run build:view && n
pm-run-posix-or-windows copy:client`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bilive_client@2.1.0 prestart script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\chy\AppData\Roaming\npm-cache\_logs\2019-05-10T01_44_13_22
0Z-debug.log

下面是那两个日志
0 info it worked if it ends with ok
1 verbose cli [ 'F:\\node.js\\node.exe',
1 verbose cli   'F:\\node.js\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build:view' ]
2 info using npm@6.4.1
3 info using node@v10.15.3
4 verbose run-script [ 'prebuild:view', 'build:view', 'postbuild:view' ]
5 info lifecycle bilive_client@2.1.0~prebuild:view: bilive_client@2.1.0
6 info lifecycle bilive_client@2.1.0~build:view: bilive_client@2.1.0
7 verbose lifecycle bilive_client@2.1.0~build:view: unsafe-perm in lifecycle true
8 verbose lifecycle bilive_client@2.1.0~build:view: PATH: F:\node.js\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;F:\bilive_client\node_modules\.bin;F:\node.js\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;F:\bilive_client\node_modules\.bin;F:\Python\Scripts\;F:\Python\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;F:\node.js\;F:\Git\Git\cmd;C:\Users\chy\AppData\Roaming\npm
9 verbose lifecycle bilive_client@2.1.0~build:view: CWD: F:\bilive_client
10 silly lifecycle bilive_client@2.1.0~build:view: Args: [ '/d /s /c',
10 silly lifecycle   'webpack --config docs/webpack.conf.js && npm-run-posix-or-windows copy:view' ]
11 silly lifecycle bilive_client@2.1.0~build:view: Returned: code: 1  signal: null
12 info lifecycle bilive_client@2.1.0~build:view: Failed to exec build:view script
13 verbose stack Error: bilive_client@2.1.0 build:view: `webpack --config docs/webpack.conf.js && npm-run-posix-or-windows copy:view`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (F:\node.js\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:189:13)
13 verbose stack     at ChildProcess.<anonymous> (F:\node.js\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:189:13)
13 verbose stack     at maybeClose (internal/child_process.js:970:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid bilive_client@2.1.0
15 verbose cwd F:\bilive_client
16 verbose Windows_NT 6.3.9600
17 verbose argv "F:\\node.js\\node.exe" "F:\\node.js\\node_modules\\npm\\bin\\npm-cli.js" "run" "build:view"
18 verbose node v10.15.3
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 1
22 error bilive_client@2.1.0 build:view: `webpack --config docs/webpack.conf.js && npm-run-posix-or-windows copy:view`
22 error Exit status 1
23 error Failed at the bilive_client@2.1.0 build:view script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

0 info it worked if it ends with ok
1 verbose cli [ 'F:\\node.js\\node.exe',
1 verbose cli   'F:\\node.js\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@6.4.1
3 info using node@v10.15.3
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle bilive_client@2.1.0~prestart: bilive_client@2.1.0
6 verbose lifecycle bilive_client@2.1.0~prestart: unsafe-perm in lifecycle true
7 verbose lifecycle bilive_client@2.1.0~prestart: PATH: F:\node.js\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;F:\bilive_client\node_modules\.bin;F:\Python\Scripts\;F:\Python\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;F:\node.js\;F:\Git\Git\cmd;C:\Users\chy\AppData\Roaming\npm
8 verbose lifecycle bilive_client@2.1.0~prestart: CWD: F:\bilive_client
9 silly lifecycle bilive_client@2.1.0~prestart: Args: [ '/d /s /c',
9 silly lifecycle   'npm run clean && npm run build:view && npm-run-posix-or-windows copy:client' ]
10 silly lifecycle bilive_client@2.1.0~prestart: Returned: code: 1  signal: null
11 info lifecycle bilive_client@2.1.0~prestart: Failed to exec prestart script
12 verbose stack Error: bilive_client@2.1.0 prestart: `npm run clean && npm run build:view && npm-run-posix-or-windows copy:client`
12 verbose stack Exit status 1
12 verbose stack     at EventEmitter.<anonymous> (F:\node.js\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
12 verbose stack     at EventEmitter.emit (events.js:189:13)
12 verbose stack     at ChildProcess.<anonymous> (F:\node.js\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
12 verbose stack     at ChildProcess.emit (events.js:189:13)
12 verbose stack     at maybeClose (internal/child_process.js:970:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
13 verbose pkgid bilive_client@2.1.0
14 verbose cwd F:\bilive_client
15 verbose Windows_NT 6.3.9600
16 verbose argv "F:\\node.js\\node.exe" "F:\\node.js\\node_modules\\npm\\bin\\npm-cli.js" "start"
17 verbose node v10.15.3
18 verbose npm  v6.4.1
19 error code ELIFECYCLE
20 error errno 1
21 error bilive_client@2.1.0 prestart: `npm run clean && npm run build:view && npm-run-posix-or-windows copy:client`
21 error Exit status 1
22 error Failed at the bilive_client@2.1.0 prestart script.
22 error This is probably not a problem with npm. There is likely additional logging output above.
23 verbose exit [ 1, true ]

**Comment by Vector000** [comment]
npm i

**Comment by chy89224** [comment]
谢谢，弱弱问句大佬有群吗

**Comment by Vector000** [comment]
并木有，本来做这个东西就是闲着蛋疼想自己加东西玩儿的，想加群可以去主分支那边看看

发送自 Windows 11

________________________________
发件人: chy89224 <notifications@github.com>
发送时间: Thursday, May 16, 2019 10:56:22 AM
收件人: Vector000/bilive_client
抄送: Vector000; Comment
主题: Re: [Vector000/bilive_client] 今天突然键入npm start出现错误，请问怎么办 (#23)


谢谢，弱弱问句大佬有群吗

―

**Comment by chy89224** [comment]
请问这个一台电脑最多可以挂多少个号？挂多少个号合适呢？
