### ISSUE TITLE
节奏风暴返回过期却继续尝试

### ISSUE THREAD

**Issue by Womsxd** [Vector000/bilive_client#25]
如题
就今天遇到了
输出：
May 14 2019 21:44:54 : ID 节奏风暴 1098378443337 第3次尝试 你错过了奖励，下次要更快一点哦~
May 14 2019 21:44:55 : ID 节奏风暴 1098378443337 第4次尝试 节奏风暴抽奖过期
May 14 2019 21:44:55 : ID 节奏风暴 1098378443337 第5次尝试 节奏风暴抽奖过期

**Comment by Vector000** [comment]
有新返回了还行，我留意一下

发送自 Windows 11

________________________________
发件人: Womsxd <notifications@github.com>
发送时间: Tuesday, May 14, 2019 9:52:54 PM
收件人: Vector000/bilive_client
抄送: Subscribed
主题: [Vector000/bilive_client] 节奏风暴返回过期却继续尝试 (#25)


如题
就今天遇到了
输出：
May 14 2019 21:44:54 : ID 节奏风暴 1098378443337 第3次尝试 你错过了奖励，下次要更快一点哦~
May 14 2019 21:44:55 : ID 节奏风暴 1098378443337 第4次尝试 节奏风暴抽奖过期
May 14 2019 21:44:55 : ID 节奏风暴 1098378443337 第5次尝试 节奏风暴抽奖过期

―

**Comment by Womsxd** [comment]
返回截图
![](https://i.bmp.ovh/imgs/2019/05/2cd9a6d1cb776dd8.jpg)
