### ISSUE TITLE
现在网页设置多了个密钥 那是啥阿

### ISSUE THREAD

**Issue by yimshing** [Vector000/bilive_client#26]
前几天还能设置 今天完全进不去

**Comment by Vector000** [comment]
密钥是用来加密通讯的，可设可不设，之前没有设定过密钥的话直接留空就可以了

发送自 Windows 11

________________________________
发件人: yimshing <notifications@github.com>
发送时间: Thursday, May 16, 2019 4:51:44 PM
收件人: Vector000/bilive_client
抄送: Subscribed
主题: [Vector000/bilive_client] 现在网页设置多了个密钥 那是啥阿 (#26)


前几天还能设置 今天完全进不去

―
