### ISSUE TITLE
启动问题

### ISSUE THREAD

**Issue by Linger12** [Vector000/bilive_client#27]
输入npm start后显示error TS6059: File 'D:/git/Git/bilive_client/app.ts' is not under 'rootDir' 'D:/git/Git/bilive_client/bilive'. 'rootDir' is expected to contain all source files.

12:30:04 - Found 1 error. Watching for file changes.
这个怎么办？

**Comment by Vector000** [comment]
额，app.ts的路径我很早就变了，怀疑你的版本太久了，建议重新clone一遍

发送自 Windows 11

________________________________
发件人: Linger12 <notifications@github.com>
发送时间: Sunday, May 19, 2019 12:33:54 PM
收件人: Vector000/bilive_client
抄送: Subscribed
主题: [Vector000/bilive_client] 启动问题 (#27)


输入npm start后显示error TS6059: File 'D:/git/Git/bilive_client/app.ts' is not under 'rootDir' 'D:/git/Git/bilive_client/bilive'. 'rootDir' is expected to contain all source files.

12:30:04 - Found 1 error. Watching for file changes.
这个怎么办？

―
