### ISSUE TITLE
账号50个左右，每次手动开启会出现403错误

### ISSUE THREAD

**Issue by zreo147** [Vector000/bilive_client#29]
账号50个左右，每次手动开启会出现403错误

希望添加一个限制插件，限制启动时比如说几分钟内可以执行几个账号的任务

执行过快发现有程序错误情况出现，谢谢

**Comment by chy89224** [comment]
正好趁这这里，请问这个一台电脑最多可以挂多少个号？挂多少个号合适呢？

**Comment by Vector000** [comment]
没有做测试，因为没有太多的号，十来个还是可以的
因为没有代理，多账号很容易会触发ip限制，建议减少挂机账号数

发送自 Windows 11

________________________________
发件人: chy89224 <notifications@github.com>
发送时间: Friday, May 31, 2019 5:23:56 PM
收件人: Vector000/bilive_client
抄送: Subscribed
主题: Re: [Vector000/bilive_client] 账号50个左右，每次手动开启会出现403错误 (#29)


正好趁这这里，请问这个一台电脑最多可以挂多少个号？挂多少个号合适呢？

―

**Comment by zreo147** [comment]
@Vector000    那大佬有考虑过代理这方面么，顺便上下TG，你好久没上线了
号多了就不太行，有的账号任务不会执行，所以想建议一个每分钟执行几个账号的任务
就像是运行错误，麻烦大佬上下TG看看聊天记录

**Comment by Vector000** [comment]
因为最近肝手游，所以一直在咕咕咕，之前设想中的很多功能都没有写
上TG的话，因为要用到不可名状的工具，过几天看看xD

发送自 Windows 11

________________________________
发件人: zreo147 <notifications@github.com>
发送时间: Saturday, June 1, 2019 1:00:02 PM
收件人: Vector000/bilive_client
抄送: Vector000; Mention
主题: Re: [Vector000/bilive_client] 账号50个左右，每次手动开启会出现403错误 (#29)


@Vector000<https://github.com/Vector000> 那大佬有考虑过代理这方面么，顺便上下TG，你好久没上线了
号多了就不太行，有的账号任务不会执行，所以想建议一个每分钟执行几个账号的任务
就像是运行错误，麻烦大佬上下TG看看聊天记录

―
