### ISSUE TITLE
Error: read ECONNRESET

### ISSUE THREAD

**Issue by BanYiMeng** [Vector000/bilive_client#32]
Jun 15 2019 23:57:09 : Error: read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:183:27) {
  errno: 'ECONNRESET',
  code: 'ECONNRESET',
  syscall: 'read'
}

**Comment by Disappear9** [comment]
https://github.com/bilive/bilive_client/issues/134

自己搭 https://github.com/bilive/bilive_server 一个吧，我一会把docker镜像发上去
