### ISSUE TITLE
建议更进下主线的反备案检测

### ISSUE THREAD

**Issue by Womsxd** [Vector000/bilive_client#35]
建议更进下主线的反备案检测
我现在是移动网络暂时没炸，可以正常使用域名，但是希望可以更新下，以防万一

**Comment by Womsxd** [comment]
大乱斗服务端也更新上去了

**Comment by zanewayne78** [comment]
求跟进，不过每天好像监听服务器有一小段时间能连上，估计是反制措施抽风
