### ISSUE TITLE
领取有概率莫名其妙的-405

### ISSUE THREAD

**Issue by Womsxd** [Vector000/bilive_client#36]
直接上图：
![2cc693f5f64f668f.jpg](https://i.loli.net/2019/06/21/5d0ce36e4031c21615.jpg)

**Comment by Vector000** [comment]
这个应该是请求超时导致抽奖太晚，尤其是现在的这个版本在抽奖前会有个模拟进房的过程（玄学）

发送自 Windows 11

________________________________
发件人: Womsxd <notifications@github.com>
发送时间: Friday, June 21, 2019 10:04:33 PM
收件人: Vector000/bilive_client
抄送: Subscribed
主题: [Vector000/bilive_client] 领取有概率莫名其妙的-405 (#36)


直接上图：
[2cc693f5f64f668f.jpg]<https://camo.githubusercontent.com/a00b1839589683117fdebcb3757406b072abb7b8/68747470733a2f2f692e6c6f6c692e6e65742f323031392f30362f32312f3564306365333665343033316332313631352e6a7067>

―

**Comment by 1873734656** [comment]
一样，有办法吗

**Comment by Vector000** [comment]
这个一般是本地的网络原因导致的请求超时，看了下我好像已经把进房模拟给弄掉了，所以这种情况基本可以确定是网络的锅
（然而我还是不能确定进房模拟跟黑屋到底有没有明确的关系，脑壳疼）

发送自 Windows 11

________________________________
发件人: hwf2000 <notifications@github.com>
发送时间: Friday, June 28, 2019 1:32:31 PM
收件人: Vector000/bilive_client
抄送: Vector000; Comment
主题: Re: [Vector000/bilive_client] 领取有概率莫名其妙的-405 (#36)


一样，有办法吗

―
