### ISSUE TITLE
关于加密

### ISSUE THREAD

**Issue by cris3980** [Vector000/bilive_client#37]
最近添加了netkey加密，然后发现导出的日志文本也是加密的，这样查看起来有点不方便

**Comment by Vector000** [comment]
会出现这样的情况吗？我用PM2导出的日志都是明文

发送自 Windows 11

________________________________
发件人: cris3980 <notifications@github.com>
发送时间: Thursday, June 27, 2019 1:29:59 AM
收件人: Vector000/bilive_client
抄送: Subscribed
主题: [Vector000/bilive_client] 关于加密 (#37)


最近添加了netkey加密，然后发现导出的日志文本也是加密的，这样查看起来有点不方便

―

**Comment by cris3980** [comment]
我没有用PM2...
