### ISSUE TITLE
怎样的配置最不容易进黑屋

### ISSUE THREAD

**Issue by OiCkilL** [Vector000/bilive_client#38]
我把丢弃比例全设成50，每天抽奖上限是40，很快就进黑屋。
这机制有点迷啊

**Comment by Vector000** [comment]
我都是不调丢弃的，风暴黑了之后就没开，黑屋随缘，几个小号轮着进，大号倒是没进过
目前看想比较稳地规避就得氪点金，我个人的经验是月费/年费老爷能部分规避普通的辣条黑屋（比如我的大号开了年费之后过一两天就出来了，几个月不进黑屋）
不氪金的话大概就得调每个账户的辣条获取上限了，以前搞过但是嫌设置项太多就弄掉了

发送自 Windows 11

________________________________
发件人: Evan <notifications@github.com>
发送时间: Friday, June 28, 2019 12:14:19 PM
收件人: Vector000/bilive_client
抄送: Subscribed
主题: [Vector000/bilive_client] 怎样的配置最不容易进黑屋 (#38)


我把丢弃比例全设成50，每天抽奖上限是40，很快就进黑屋。
这机制有点迷啊

―

**Comment by By-Ha** [comment]
果然还是要氪金啊
