### ISSUE TITLE
关于登录状态

### ISSUE THREAD

**Issue by cris3980** [Vector000/bilive_client#39]
{ code: -401, data: null, message: '请先登录哦', msg: '请先登录哦' }
cookie 到期了有时候会登录不上，也不会重新登录，是否可以加个推送？
还有一个账号密码更改的bug，在原来的用户上直接更改不会生效，必须新建一个用户重新填写才行。

**Comment by cris3980** [comment]
好像昨天中午B站升级了，挂不到在线经验了

**Comment by chy89224** [comment]
请问这个怎么办
21:11:38 - Starting compilation in watch mode...


21:11:43 - Found 0 errors. Watching for file changes.
undefined:1



SyntaxError: Unexpected token

**Comment by Vector000** [comment]
> { code: -401, data: null, message: '请先登录哦', msg: '请先登录哦' }
> cookie 到期了有时候会登录不上，也不会重新登录，是否可以加个推送？
> 还有一个账号密码更改的bug，在原来的用户上直接更改不会生效，必须新建一个用户重新填写才行。

cookie是随着PC端心跳更新的，5分钟一次，一般都能成功更新
在前端页面直接修改账号密码的话，需要先取消勾选解除登录状态，再进行修改。程序里面没有直接修改账密后触发用户更新的逻辑
