### ISSUE TITLE
vector000.coding.me/bilive_setting/经常连不上

### ISSUE THREAD

**Issue by ReginWong** [Vector000/bilive_client#40]

**Comment by Vector000** [comment]
刚刚看了下，应该是DNS的锅，国内基本全TM是超时，辣鸡tx云（
有能力的话，可以改host
119.28.76.36 vector000.coding.me
其实还是推荐用本地的设置页面，tx云的page服务在HK…

发送自 Windows 11

________________________________
发件人: ReginWong <notifications@github.com>
发送时间: Sunday, July 14, 2019 11:56:40 AM
收件人: Vector000/bilive_client
抄送: Subscribed
主题: [Vector000/bilive_client] vector000.coding.me/bilive_setting/经常连不上 (#40)


―
