### ISSUE TITLE
关于消息问题

### ISSUE THREAD

**Issue by Linger12** [Vector000/bilive_client#42]
每次启动都会显示服务器11月到期，这个是什么意思？

**Comment by pjy612** [comment]
因为11月会到期

**Comment by Linger12** [comment]
我就是想知道11月过期了是不是就用不了了？

**Comment by sxinxins** [comment]
yes

**Comment by Linger12** [comment]
到期后会不会给东西自己弄，我相信作者不会弃坑吧，汗！

**Comment by pjy612** [comment]
作者不是还有个Server 端么？你自己架设一下呗。。。

**Comment by Linger12** [comment]
server端为什么看不到舰队抽奖那些，感觉比bilive上的信息少好多，节奏也没看见

**Comment by pjy612** [comment]
emmm server 端 就是 你用 client 连接的那个。。。作者的server 11月到期。。。
监控在 server 推送给 client ，client 去抽奖

**Comment by Vector000** [comment]
提供了一个备用服务器
