### ISSUE TITLE
大佬，更新抽奖插件呀

### ISSUE THREAD

**Issue by ShmilyChen** [Vector000/bilive_client#43]
同步一下主分支的抽奖插件吧，pk活动又来了

**Comment by cris3980** [comment]
自己试着把从主分支的移植过来，水平有限卡这了
bilive/plugins/raffle/raffle.ts[36m(74,9): error TS2678: [39mType '"pklottery"' is not comparable to type '"smallTV" | "raffle" | "lottery" | "beatStorm"'.

**Comment by Vector000** [comment]
等我把私有分支那几个commit合并过来就好了（）

发送自 Windows 11

________________________________
发件人: ShmilyChen <notifications@github.com>
发送时间: Tuesday, July 23, 2019 11:57:20 PM
收件人: Vector000/bilive_client <bilive_client@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: [Vector000/bilive_client] 大佬，更新抽奖插件呀 (#43)


同步一下主分支的抽奖插件吧，pk活动又来了

―
