### ISSUE TITLE
签到接口下线

### ISSUE THREAD

**Issue by cris3980** [Vector000/bilive_client#46]
自动签到 { code: -1, msg: '该接口已下线', message: '该接口已下线', data: [] }

**Comment by ShmilyChen** [comment]
网页端是`https://api.live.bilibili.com/sign/doSign`
返回值`{"code":0,"msg":"OK","message":"OK","data":{"text":"6000用户经验值,4辣条,600友爱金","specialText":"(再签到2天可以获得3天月费老爷)","allDays":31,"hadSignDays":8,"isBonusDay":0}}`

**Comment by ShmilyChen** [comment]
将`bilive/plugins/sign/index.ts`中第49行中的`https://api.live.bilibili.com/AppUser/getSignInfo`替换成`https://api.live.bilibili.com/rc/v1/Sign/doSign`即可

**Comment by cris3980** [comment]
@ShmilyChen 我才换完你前面发的网页端

**Comment by ShmilyChen** [comment]
我刚才去抓的app端，还测试了

**Comment by cris3980** [comment]
网页端的试了可以用，不行下次再换了

**Comment by cris3980** [comment]
@1499049630 换完要run build
