### ISSUE TITLE
特定用户的Server酱推送接收不到

### ISSUE THREAD

**Issue by heitu001** [Vector000/bilive_client#48]
特定用户的Server酱SCKEY填写好之后，并没有收到通知。
adminSCKEY 正常推送
请教一下大佬这是什么问题！【很迷】

**Comment by cris3980** [comment]
用户的只会接收到停止挂机，封禁能不能忘了，这是因为消息分类的原因

**Comment by heitu001** [comment]
期待大大后期有时间可以改进一下，增加点和管理员一样的结算报告之类的！⁄(⁄ ⁄•⁄ω⁄•⁄ ⁄)⁄

**Comment by Vector000** [comment]
单user的SC推送是后面才跟随主分支引入的功能，之前做的那些消息推送全部都是走的管理员SCKEY，所以你收不到东西其实是正常操作，因为根本就没有东西发
分用户结算报告其实可以做一下，不过要考虑到方糖那边对IP的限制，还不能多发

**Comment by cris3980** [comment]
自己搞QQ机器人推送倒也不错

**Comment by ShmilyChen** [comment]
> 单user的SC推送是后面才跟随主分支引入的功能，之前做的那些消息推送全部都是走的管理员SCKEY，所以你收不到东西其实是正常操作，因为根本就没有东西发
> 分用户结算报告其实可以做一下，不过要考虑到方糖那边对IP的限制，还不能多发

弄成队列，分批发送，反正这个也不求时间非常准确
