### ISSUE TITLE
插件问题

### ISSUE THREAD

**Issue by xianyunb** [Vector000/bilive_client#49]
原作者lzghzr的插件能不能直接在这上面安装使用

**Comment by fs779** [comment]
对呀，最近老是弹验证码错误，希望可以搞一下Ծ ̮ Ծ

**Comment by Vector000** [comment]
不能直接用，要兼容的话需要做改动

发送自 Windows 11

________________________________
发件人: fs779 <notifications@github.com>
发送时间: Sunday, August 18, 2019 1:16:58 AM
收件人: Vector000/bilive_client <bilive_client@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: Re: [Vector000/bilive_client] 插件问题 (#49)


对呀，最近老是弹验证码错误，希望可以搞一下Ծ ̮ Ծ

**Comment by xianyunb** [comment]
希望大佬能加下原作者那样的QQsever，感觉比微信的好用

**Comment by Linger12** [comment]
希望加一个QQserver,毕竟QQ经常使用，方便一些
