### ISSUE TITLE
关于节奏风暴

### ISSUE THREAD

**Issue by IMNOTHD** [Vector000/bilive_client#53]
多个节奏风暴同时抽奖非常容易被判定412
能否添加功能控制单个用户同时抽的节奏风暴的数量

**Comment by fjf010223** [comment]
原来412是这个原因么，不手动停的话会一直412吗

**Comment by fjf010223** [comment]
不过412的时候我手动去领还是能领到是为什么。。。

**Comment by IMNOTHD** [comment]
其实这个412是POST过多，对发包ip判定ddos，短暂拦截15分钟
