### ISSUE TITLE
最近经常出现的错误

### ISSUE THREAD

**Issue by fjf010223** [Vector000/bilive_client#61]
Oct 15 2019 19:05:42 : https://api.live.bilibili.com/lottery/v2/lottery/join { Error: connect ETIMED
OUT 服务器IP地址:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '服务器IP地址',
  port: 443 }

虽然不会使脚本停止，但好像会使部分功能间歇性失效，比如自动领取银瓜子

**Comment by fjf010223** [comment]
Oct 15 2019 19:15:24 : https://space.bilibili.com/ajax/member/getSubmitVideos?mid=451066708&pagesize
=50&tid=0 { Error: connect ETIMEDOUT 106.75.162.231:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '106.75.162.231',
  port: 443 }

好像还不止一种

**Comment by Linger12** [comment]
自动投喂过期礼物和V2送礼都失效了
