### ISSUE TITLE
bilive现在领取的舰长亲密度奖励可视为额外亲密度

### ISSUE THREAD

**Issue by fjf010223** [Vector000/bilive_client#64]
如标题所说，我偶然间发现bilive现在领取的舰长亲密度会正确计算，但是进入刚刚领取过奖励的直播间，无一例外都显示舰长奖励还没领取，自己可以再点一次，个人猜测是不是因为bilive好久没更新了的原因，接口还是旧的，但B站还没弃用？
于是我想到配合其他脚本（适配了新接口的）自动再领一次的话，相当于双倍舰长亲密度奖励，而且这个奖励不计入每日上限，很舒服，也不知道还能享受几天

**Comment by cris3980** [comment]
同发现
https://api.live.bilibili.com/xlive/lottery-interface/v3/guard/join  貌似改解析
