### ISSUE TITLE
 出现了{ code: 400, msg: '请升级app', message: '请升级app', data: [] }

### ISSUE THREAD

**Issue by 1604589485** [Vector000/bilive_client#68]
{ code: 400, msg: '请升级app', message: '请升级app', data: [] }怎么办

**Comment by 1604589485** [comment]
是舰队抽奖

**Comment by Vector000** [comment]
老接口被屏蔽了，双倍舰长的快乐结束了

发送自 Windows 11

________________________________
发件人: 1604589485 <notifications@github.com>
发送时间: Monday, January 20, 2020 9:50:16 PM
收件人: Vector000/bilive_client <bilive_client@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: Re: [Vector000/bilive_client] 出现了{ code: 400, msg: '请升级app', message: '请升级app', data: [] } (#68)


是舰队抽奖

―
