### ISSUE TITLE
403拒绝访问

### ISSUE THREAD

**Issue by cris3980** [Vector000/bilive_client#7]
{ code: -403, data: null, message: '访问被拒绝', msg: '访问被拒绝' }
这阵子有了403拒绝访问，然后自动禁抽跟推送就GG了

**Comment by Vector000** [comment]
code改-403有一段时间了，所以我挺久之前就改成msg判据了

发送自 Windows 11 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: cris3980 <notifications@github.com>
发送时间: Friday, March 29, 2019 2:48:59 PM
收件人: Vector000/bilive_client
抄送: Subscribed
主题: [Vector000/bilive_client] 403拒绝访问 (#7)


{ code: -403, data: null, message: '访问被拒绝', msg: '访问被拒绝' }
这阵子有了403拒绝访问，然后自动禁抽跟推送就GG了

―
