### ISSUE TITLE
Utils userCheck List 存在无效数据

### ISSUE THREAD

**Issue by StringKe** [Vector000/bilive_client#81]
![image](https://user-images.githubusercontent.com/31089228/76157399-65645a00-6143-11ea-9d10-7eb804bc8620.png)
这里实际上只有存在一个用户的
![image](https://user-images.githubusercontent.com/31089228/76157404-7745fd00-6143-11ea-9c8c-b1c59060c990.png)

**Comment by Vector000** [comment]
是从未见过的bug 我死了
不过我倒是定位到了一个可能的原因

**Comment by StringKe** [comment]
> 是从未见过的bug 我死了
> 不过我倒是定位到了一个可能的原因

就这个，好像是基于事件的异步操作。。。我想改成你httpapi的方式。。。已经开始懵了

**Comment by StringKe** [comment]
我看到你更新了，webapi.ts 会导致 webapi http方式的没有返回内容。。。
