### ISSUE TITLE
大佬，怎么在把这个挂在VPS上？

### ISSUE THREAD

**Issue by DoedKr** [Vector000/bilive_client#84]
最近在想VPS只用来搭梯子挺浪费的，就想把这个也挂到上面。现在的问题是如果挂在VPS上了我要怎么打开index设置东西呢？

**Comment by pixia1234** [comment]
> 最近在想VPS只用来搭梯子挺浪费的，就想把这个也挂到上面。现在的问题是如果挂在VPS上了我要怎么打开index设置东西呢？

emmmm这不是很简单嘛

**Comment by HellSakura** [comment]
> 最近在想VPS只用来搭梯子挺浪费的，就想把这个也挂到上面。现在的问题是如果挂在VPS上了我要怎么打开index设置东西呢？

建议先学一下Linux的基本操作。。。。

**Comment by DoedKr** [comment]
> 
> 
> > 最近在想VPS只用来搭梯子挺浪费的，就想把这个也挂到上面。现在的问题是如果挂在VPS上了我要怎么打开index设置东西呢？
> 
> emmmm这不是很简单嘛

好吧...原来真的是很简单...和我预想的一样啊...只是我没有敢去先尝试一下....

**Comment by DoedKr** [comment]
> 
> 
> > 最近在想VPS只用来搭梯子挺浪费的，就想把这个也挂到上面。现在的问题是如果挂在VPS上了我要怎么打开index设置东西呢？
> 
> 建议先学一下Linux的基本操作。。。。

感谢，已经不用了，nano改一下json就完事了...我最先是这么想的但没敢尝试一下。哈哈
