### ISSUE TITLE
当号出现问题后 登不上 然后死循环

### ISSUE THREAD

**Issue by Sakura9s** [Vector000/bilive_client#87]
账号出现问题后(异常和密码错误），程序就会一直卡在登入那里，因为没接入监控，就index.html就连不上  连不上就改不了密码 改不了密码就一直登 于是就死循环了 只能全删了从新来过  号少的话还行，号多的话直接GG

**Comment by HellSakura** [comment]
这时候请直接去程序目录的`options.json`，将出问题的账号的`"status"`改为`false`
这时候就能连接成功了。
这个问题好像是触发了登录设备验证导致的，b站好像昨天将多ip登录的号都强制下线了一次。

**Comment by Sakura9s** [comment]
> 这时候请直接去程序目录的`options.json`，将出问题的账号的`"status"`改为`false`
> 这时候就能连接成功了。
> 这个问题好像是触发了登录设备验证导致的，b站好像昨天将多ip登录的号都强制下线了一次。

谢谢
Thanks♪(･ω･)ﾉ
