### ISSUE TITLE
扩展化接口？

### ISSUE THREAD

**Issue by StringKe** [Vector000/bilive_client#9]
https://github.com/Vector000/bilive_client/blob/c205b2718fbfe0c4ad56fc15cb99df858dc04619/bilive/webapi.ts#L21

这个功能后续可以使用http接口来管理么？

**Comment by Vector000** [comment]
emm目前没有这个想法，将来应该也不会，因为实在不熟悉http接口，现在用websocket连接还是能用的233

**Comment by StringKe** [comment]
我想找你定制开发一下，微信投喂找过你，233

**Comment by Vector000** [comment]
惊了2333

**Comment by StringKe** [comment]
我留个 5oiR55qEcXHvvJogMjQ3OTkyMTY2MQrmiJHnmoR3eO+8mmI4ODg4LTg4ODhk  欢迎骚扰我～～～

**Comment by StringKe** [comment]
BASE64
