### ISSUE TITLE
app版本似乎该更新了

### ISSUE THREAD

**Issue by lovezm** [Vector000/bilive_client#90]
登录一直提示繁忙 稍后重试

**Comment by pixia1234** [comment]
+1,情况一样

**Comment by lovezm** [comment]
改成v3接口就好了。

**Comment by pixia1234** [comment]
怎么弄？？

**Comment by Billyzou0741326** [comment]
@pixia1234 https://github.com/Vector000/bilive_client/blob/e538ec9d62be6dc6c5b9751830ef1d7a13aaf436/bilive/lib/app_client.ts#L269
` uri: 'https://passport.bilibili.com/api/v3/oauth2/login', `

**Comment by pixia1234** [comment]
还是一样的问题

**Comment by Billyzou0741326** [comment]
确定有重新编译吗

**Comment by Billyzou0741326** [comment]
不过我也没测 不确定...

**Comment by pixia1234** [comment]
解决了，谢谢大佬

**Comment by Billyzou0741326** [comment]
客气了... 我菜
