### ISSUE TITLE
Token更新失败 { code: -449, message: '服务繁忙, 请稍后再试', ts: 1585955139 }

### ISSUE THREAD

**Issue by pixia1234** [Vector000/bilive_client#91]
Token更新失败 { code: -449, message: '服务繁忙, 请稍后再试', ts: 1585955139 }怎么办

**Comment by xianyunb** [comment]
我也是这样，咋办啊

**Comment by pixia1234** [comment]
> 我也是这样，咋办啊

已解决，把登陆端口改成v3即可

**Comment by Sakura9s** [comment]
> > 我也是这样，咋办啊
> 
> 已解决，把登陆端口改成v3即可

大佬怎么换V3接口？-_-||

**Comment by pixia1234** [comment]
查issue
