### ISSUE TITLE
服务繁忙, 请稍后再试

### ISSUE THREAD

**Issue by Sakura9s** [Vector000/bilive_client#96]
应该是登录接口换了。

Apr 15 2020 11:01:19 : **** Cookie已失效
Apr 15 2020 11:01:19 : **** Token已失效
Apr 15 2020 11:01:19 : **** 已停止挂机
Apr 15 2020 11:01:19 : **** Token更新失败 { code: -449, message: '服务繁忙, 请稍后再试', ts: ****}

**Comment by Lozumi** [comment]
同，vector没动静乐

**Comment by DoedKr** [comment]
一样，突然就这样了。现在服务器上边登不上，但是本地却没问题。我怀疑是不是被封IP之类的了...

**Comment by Modilay** [comment]
一样。。昨天还行，今天就token更新失败了，本地可以，服务器就GG了

**Comment by DoedKr** [comment]
> 
> 
> 一样。。昨天还行，今天就token更新失败了，本地可以，服务器就GG了

那看来是阿B那边的事了

**Comment by SakuraKoi** [comment]
提供一个方法,本地登录后把配置文件里的token复制到服务器上的配置文件里
我这边有一个帐号碰到这个问题了

**Comment by DoedKr** [comment]
> 
> 
> 提供一个方法,本地登录后把配置文件里的token复制到服务器上的配置文件里
> 我这边有一个帐号碰到这个问题了

已经解决了
是登录接口的问题，改了就好
